overrides:
  eslint: "~8.57.0"
  nth-check: ">=2.0.1"
  serialize-javascript: ">=7.0.5"
  underscore: ">=1.13.8"
  webpack-dev-server: ">=5.2.4"
  uuid: ">=11.1.1"
  js-yaml: ">=4.2.0"
  "@opentelemetry/core": ">=2.8.0"
  "@tootallnate/once": ">=2.0.1"

allowBuilds:
  aws-sdk: false
  core-js: false
  core-js-pure: false
